language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm-nightly

env:
  - SYMFONY_VERSION=2.2.*
  - SYMFONY_VERSION=2.3.*
  - SYMFONY_VERSION=2.4.*
  - SYMFONY_VERSION=dev-master

before_script:
  - composer require symfony/symfony:${SYMFONY_VERSION} --prefer-source
  - composer install --dev --prefer-source

script: phpunit

notifications:
  email:
    - vincent.composieux@gmail.com

matrix:
  allow_failures:
    - php: hhvm-nightly
